# Generated by Django 3.2.5 on 2024-04-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callback", "0002_auto_20240409_0214"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerGame",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="callback.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="callback.player",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="game",
            name="players",
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                blank=True,
                related_name="player_games",
                through="callback.PlayerGame",
                to="callback.Player",
            ),
        ),
    ]
