# Generated by Django 3.2.5 on 2024-04-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callback", "0003_auto_20240409_0259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="email",
            field=models.EmailField(max_length=54, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(default="", max_length=54, unique=True),
        ),
    ]
